Fix import error
A newer version of pip was causing the following import error:

Traceback (most recent call last):
  File "./setup.py", line 27, in <module>
    from pip.req import parse_requirements
ImportError: No module named req
Traceback (most recent call last):
  File "./setup.py", line 27, in <module>
    from pip.req import parse_requirements
ImportError: No module named req

The import has been changed to use the new syntax and fallback if
using old pip to keep compatibility.